// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALguXIAbAWwxtLHANhSgDVBklm68SJEOc',
    appId: '1:615028403790:web:103f8b8e741aaeeab69d1f',
    messagingSenderId: '615028403790',
    projectId: 'my-first-firebase-for-flutter',
    authDomain: 'my-first-firebase-for-flutter.firebaseapp.com',
    storageBucket: 'my-first-firebase-for-flutter.firebasestorage.app',
    measurementId: 'G-FESE77W9DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB74mSVf-6KrIvvBIDaR3aaP9I4uS7ye1w',
    appId: '1:615028403790:android:e585b4058a363e6fb69d1f',
    messagingSenderId: '615028403790',
    projectId: 'my-first-firebase-for-flutter',
    storageBucket: 'my-first-firebase-for-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL8j8XjW4QzoMMofQyk9icyP_vXZ6gIxg',
    appId: '1:615028403790:ios:7c4fda6e3579f9dcb69d1f',
    messagingSenderId: '615028403790',
    projectId: 'my-first-firebase-for-flutter',
    storageBucket: 'my-first-firebase-for-flutter.firebasestorage.app',
    iosBundleId: 'com.example.bookManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL8j8XjW4QzoMMofQyk9icyP_vXZ6gIxg',
    appId: '1:615028403790:ios:7c4fda6e3579f9dcb69d1f',
    messagingSenderId: '615028403790',
    projectId: 'my-first-firebase-for-flutter',
    storageBucket: 'my-first-firebase-for-flutter.firebasestorage.app',
    iosBundleId: 'com.example.bookManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALguXIAbAWwxtLHANhSgDVBklm68SJEOc',
    appId: '1:615028403790:web:6a6b4de1ec4519a5b69d1f',
    messagingSenderId: '615028403790',
    projectId: 'my-first-firebase-for-flutter',
    authDomain: 'my-first-firebase-for-flutter.firebaseapp.com',
    storageBucket: 'my-first-firebase-for-flutter.firebasestorage.app',
    measurementId: 'G-Q4CCW3TEKL',
  );
}
